### ISSUE TITLE
Make a list of all surveys/systematic reviews of prompting/prompt engineering

### ISSUE THREAD

**Issue by trigaten** [trigaten/Prompt_Systematic_Review#38]

**Comment by sauravv15** [comment]
Meskó, Bertalan. "Prompt engineering as an important emerging skill for medical professionals: tutorial." Journal of Medical Internet Research 25 (2023): e50638.

Wang, Jiaqi, et al. "Review of large vision models and visual prompt engineering." arXiv preprint arXiv:2307.00855 (2023).

Heston, Thomas F., and Charya Khun. "Prompt engineering in medical education." International Medical Education 2.3 (2023): 198-205.

Gao, Andrew. "Prompt Engineering for Large Language Models." Available at SSRN 4504303 (2023).

Neagu, Alexandra. "How can large language models and prompt engineering be leveraged in Computer Science education?: Systematic literature review." (2023).

Dang, Hai, et al. "How to prompt? Opportunities and challenges of zero-and few-shot learning for human-AI interaction in creative applications of generative models." arXiv preprint arXiv:2209.01390 (2022).

Liu, Pengfei, et al. "Pre-train, prompt, and predict: A systematic survey of prompting methods in natural language processing." ACM Computing Surveys 55.9 (2023): 1-35.

Meyer, Jesse G., et al. "ChatGPT and large language models in academia: opportunities and challenges." BioData Mining 16.1 (2023): 20.

Hou, Xinyi, et al. "Large language models for software engineering: A systematic literature review." arXiv preprint arXiv:2308.10620 (2023).

Nguyen, Josh, and Christopher A. Pepping. "The application of ChatGPT in healthcare progress notes: a commentary from a clinical and research perspective." Clinical and Translational Medicine 13.7 (2023).

Wang, Junjie, et al. "Software testing with large language model: Survey, landscape, and vision." arXiv preprint arXiv:2307.07221 (2023).

Zhang, Quanjun, et al. "A Critical Review of Large Language Model on Software Engineering: An Example from ChatGPT and Automated Program Repair." (2023).

Lou, Renze, Kai Zhang, and Wenpeng Yin. "Is prompt all you need? no. A comprehensive and broader view of instruction learning." arXiv preprint arXiv:2303.10475 (2023).

Liu, Peng, Lemei Zhang, and Jon Atle Gulla. "Pre-train, prompt and recommendation: A comprehensive survey of language modelling paradigm adaptations in recommender systems." arXiv preprint arXiv:2302.03735 (2023).

Wang, Shuai, et al. "Can ChatGPT write a good boolean query for systematic review literature search?." arXiv preprint arXiv:2302.03495 (2023).

Li, Yingji, et al. "A Survey on Fairness in Large Language Models." arXiv preprint arXiv:2308.10149 (2023).

Ko, Hyung-Kwon, et al. "Large-scale text-to-image generation models for visual artists’ creative works." Proceedings of the 28th International Conference on Intelligent User Interfaces. 2023.

Awais, Muhammad, et al. "Foundational models defining a new era in vision: A survey and outlook." arXiv preprint arXiv:2307.13721 (202

Hadi, Muhammad Usman, et al. "Large Language Models: A Comprehensive Survey of its Applications, Challenges, Limitations, and Future Prospects." (2023).

Qiu, Jianing, et al. "Large ai models in health informatics: Applications, challenges, and the future." IEEE Journal of Biomedical and Health Informatics (2023).

Wang, Ding‐Qiao, et al. "Accelerating the integration of ChatGPT and other large‐scale AI models into biomedical research and healthcare." MedComm–Future Medicine 2.2 (2023): e43.

Clusmann, Jan, et al. "The future landscape of large language models in medicine." Communications Medicine 3.1 (2023): 141.

**Comment by trigaten** [comment]
Sallam M. ChatGPT utility in healthcare education, research, and practice: systematic review on the promising perspectives and valid concerns. Healthcare (Basel) 2023 Mar 19;11(6) doi: 10.3390/healthcare11060887. https://www.mdpi.com/resolver?pii=healthcare11060887 .healthcare11060887 [[PMC free article](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10048148/)] [[PubMed](https://pubmed.ncbi.nlm.nih.gov/36981544)] [[CrossRef](https://doi.org/10.3390%2Fhealthcare11060887)] [[Google Scholar](https://scholar.google.com/scholar_lookup?journal=Healthcare+(Basel)&title=ChatGPT+utility+in+healthcare+education,+research,+and+practice:+systematic+review+on+the+promising+perspectives+and+valid+concerns&author=M+Sallam&volume=11&issue=6&publication_year=2023&doi=10.3390/healthcare11060887&)]
