### ISSUE TITLE
Properly format paper in NAACL style

### ISSUE THREAD

**Issue by trigaten** [trigaten/Prompt_Systematic_Review#41]
Like this paper: https://www.overleaf.com/read/ssnjbdvsbphf#9d931e

**Comment by sauravv15** [comment]
Paper is formatted to match the style. Will make extra changes to allow for easy changes and additions of paper sections.

**Comment by trigaten** [comment]
Please format as NAACL instead: https://2024.naacl.org

**Comment by trigaten** [comment]
Not a priority rn
