### ISSUE TITLE
Fix keyword search pipeline

### ISSUE THREAD

**Issue by trigaten** [trigaten/Prompt_Systematic_Review#51]
Currently, keywords like "prompt learning" are being searched as "prompt" and "learning". This gives us many random papers that we do not need.

**Comment by ahoho** [comment]
I think this sort of thing is addressed in other systematic review papers, but I think the typical approach is to write up a set of boolean queries

"prompt and (LLM or ChatGPT)" sort of stuff.

It's my understanding that this is also the standard in legal discovery, where basically a small miss in recall can end up costing a million-dollar case.

**Comment by Mcilie** [comment]
this is fixed in my PR #53
