### ISSUE TITLE
Human Review of Dataset

### ISSUE THREAD

**Issue by trigaten** [trigaten/Prompt_Systematic_Review#66]
- Add irrelevant papers to https://github.com/trigaten/Prompt_Systematic_Review/blob/main/data/blacklist.csv
- Make sure to add your reasoning for removal

FAQ: 
- In context learning is not always an appropriate paper. For example, if it is proposing some new attention framework (Improving Input-label Mapping with Demonstration Replay for In-context Learning)

HOW TO DO THIS:
Read the TITLE of the paper from the CSV file first. If you are not SURE that it relates to hard prefix prompting, take a look at the PAPER itself. Then, if you feel it is not relevant, add it to `data/blacklist `

IF YOU ARE NOT SURE about a paper:
Post it in #paper-removal and tag @Sander

Here are the row assignments. The CSV is linked in my comment below. It has all the papers, their titles, and links. Also DM me if you find new prompting techniques :)
@trigaten 1-100
@Mcilie 101-500
@asl3 501-700
@hudssntao 701-900
@ashay-sriv-06 901-1000
@pranavdulepet 1001-1100
@Alexander 1101-1300
@kkahadze 1301-1400
@AayushGupta16 1400-1661

**Comment by trigaten** [comment]
I am doing rows 1-100

**Comment by trigaten** [comment]
[arxiv_papers.csv](https://github.com/trigaten/Prompt_Systematic_Review/files/13314518/arxiv_papers.csv)

**Comment by ahoho** [comment]
we should have some overlap of at least one set of these to measure inter-annotator agreement

**Comment by ahoho** [comment]
also is there a reason we aren't just doing this in a google sheet we can all edit?

**Comment by trigaten** [comment]
> we should have some overlap of at least one set of these to measure inter-annotator agreement

Agreed, I will look to do this after we get them completed.

> also is there a reason we aren't doing this on google sheets so we can all edit in place?

I don't see it providing a significant efficiency boost. It is most efficient for me to have the csv open and quickly CTRL+click on each link as needed. If a Sheet is easier for you or others, please do it that way and I will merge results.
