### ISSUE TITLE
Unify paper pipeline with multilingual

### ISSUE THREAD

**Issue by trigaten** [trigaten/Prompt_Systematic_Review#87]
We should either include ACL Anthology in our pipeline or show that semantic can get all sources they used, so we can have a single dataset of papers. Then multilingual can say "we used our collected dataset then searched for papers with the word "lingual". The word "prompt" is already checked for in our main data pipeline.

> 8.1 Paper collection
To ensure a comprehensive and methodical collec-
tion of papers, we employ a structured paper collec-
tion procedure, as outlined in Blodgett et al. (5). Ini-
tially, we searched papers from the ACL Anthology
for papers containing the keywords “prompt” and
“lingual,” with a publication date prior to November
>2023. Additionally, for Section 8.3 of our survey,
which focuses on translation tasks, we refine our
search to include papers that intersected with the
keywords “prompt” and “translation.”
We also manually traversed Google scholar and

**Comment by Mcilie** [comment]
Addressed by adding ACL anthology
